
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled

- name: restart elasticsearch
  become: yes
  systemd: name=elasticsearch state=restarted enabled=yes daemon_reload=true
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
